### ISSUE TITLE
Add hairlines/divider lines back into lists in cards

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic2#272]
such that we can get an effect like this (for the Docs):

![image](https://cloud.githubusercontent.com/assets/519526/10435234/4acc7db6-70e4-11e5-96b9-4aad028945ae.png)

**Comment by brandyscarney** [comment]
So the items in this demo aren't actually in an `ion-list` they are just there. The markup looks like this:

```
<ion-card class="cards-list-demo">

      <ion-card-header>
        Explore Nearby
      </ion-card-header>

      <a href="#" ion-item>
        <icon cart item-left></icon>
        Shopping
      </a>

      <a href="#" ion-item>
        <icon medical item-left></icon>
        Hospital
      </a>
</ion-card>
```

So do you want the items to be wrapped in an `ion-list` and then modify the padding that is being added from being inside of an `ion-card` (as mentioned in https://github.com/driftyco/ionic2/issues/278) or do you want to just apply the list styling to all items in a card regardless if within a list?

I don't think applying it to all items in a card is a good way to go, because some users may not want list styling on the items in the card.

**Comment by adamdbradley** [comment]
We should create a new attribute that removes borders from card and list items.

**Comment by brandyscarney** [comment]
I'm confused. Ben wants the borders added.

**Comment by adamdbradley** [comment]
Sorry. Add the borders back in by default, but a new attr to explicitly remove them.

**Comment by brandyscarney** [comment]
Adam and I discussed this and I added some things to do on this issue #387 which will ultimately fix this.

**Comment by brandyscarney** [comment]
Spoke to Ben, he said we don't need to do this.
