### ISSUE TITLE
button: primary clear button active state is wrong 

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#354]
When using a clear button inside of a card:

```
  <ion-item actions>
      <button primary clear item-left>
        <icon thumbs-up></icon>
        46 Likes
      </button>
  </ion-item>
```

the button's active state will be a solid color from `primary` attribute, when it should be mostly transparent.

**Comment by brandyscarney** [comment]
This is actually caused by the primary attribute on the clear button, if you remove the primary attribute it will fix this for your demo, but I'll work on a more permanent fix.

![screen shot 2015-10-27 at 4 07 52 pm](https://cloud.githubusercontent.com/assets/6577830/10771038/fd2f5d98-7cc4-11e5-88ee-f2a93ddada66.png)
