### ISSUE TITLE
iOS: Segment bar styling in toolbar is wrong

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#356]
If there are two segments it looks fine but 3 causes it to ellipsis and not expand width, also segment bar with 4 buttons shows a large border in the middle.

![screen shot 2015-10-27 at 5 25 27 pm](https://cloud.githubusercontent.com/assets/6577830/10773080/c197875a-7ccf-11e5-91d7-a8f4e72b185d.png)

**Comment by brandyscarney** [comment]
The structure behind the `ion-toolbar` and `.ios ion-title` will need to be changed for this to work. I can remove the padding that gets added but then when buttons are added in the toolbar it will not work with them. This will affect all iOS toolbars so it should be discussed.

![screen shot 2015-10-27 at 6 07 17 pm](https://cloud.githubusercontent.com/assets/6577830/10774173/0e6d32b8-7cd6-11e5-9357-1ca879b19687.png)

**Comment by adamdbradley** [comment]
ion-title is a real challenge, because of the centering, and you could have any number of buttons on the left or right side of it. You could have two buttons on the right side, and no buttons on the left, but the title still needs to be centered.

toolbar/scenarios e2e tests would probably be the best place to start experimenting with some ideas. Right now it's got a generic 90px padding on the left and right, but we'll need to have it dynamically figure out the centering like how v1 does it. But the challenge is to do it without causing reflows at the wrong times during an animation.

**Comment by adamdbradley** [comment]
Been thinking about this. I think it should be that `<ion-title>` is only for text. So an `<ion-segement>` should fit in there well, even when not within ion-title. We'll probably have to update the ng-content select for navbars/toolbars to allow this to work.

**Comment by brandyscarney** [comment]
Get rid of the `.ion-segment` div

**Comment by mlynch** [comment]
@adamdbradley that would be kind of counter to iOS, where the title area can have any UI element. If ion-title has proper sizing and centering, that seems like it'd be a good place to also put other elements like segment?

**Comment by adamdbradley** [comment]
@mlynch the problem is that ion-title is doing a lot of magic to center the text no matter how many buttons are on either side. And because of that magic it makes other elements inside of ion-title difficult to center. I think it'd be better to not overload ion-title with too much, and leave its responsibilities to just text.

**Comment by brandyscarney** [comment]
This is actually fixed if it's fine that `ion-segment` isn't in an `ion-title`. @adamdbradley good to close?

**Comment by adamdbradley** [comment]
:8ball:
