### ISSUE TITLE
Plan for moving Push Plugin and Touch Id plugins to the platform.

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#394]
Hi ,
You guys are  doing great job just wanted to know when will the support for Push plugin and Touch Id platform will land in Ionic 2.

**Comment by nihgwu** [comment]
I really don't think to add native plugin to the core package is a good idea, please refer to #336 , and i have to say that, in China the Push plugin is just won't work because all the Google's service are blocked so we have to use a alternative to do with that
So just keep the core clean and small will be better

**Comment by ajaybeniwal** [comment]
I understand but since they have decided to keep to core at this point I do not have any other option but to follow it and use there platform services

**Comment by nihgwu** [comment]
you can write your own one :smile:

**Comment by mlynch** [comment]
we have a plan forward for this, going to just expose the whole of cordova plugins and help document it.
