### ISSUE TITLE
Bottom Tab bar not hidden on child pages

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#416]
Bottom tab par is not hidden on the child pages ideally on the child navigation pages tab bar should be hidden

**Comment by adamdbradley** [comment]
iOS or Android?

**Comment by ajaybeniwal** [comment]
IOS not checked on Android

**Comment by adamdbradley** [comment]
Maybe I'm not understanding correctly, but iOS does not hide the tab bar on child navigation pages. Can you explain the scenario of when the tab bar would be hidden on iOS?

**Comment by ajaybeniwal** [comment]
If you see whatsapp APP or skype app when you click on any list item and navigate to inner page the bottom tab par will not be visible at all, I think It should be user configurable to show tab bar or not on inner page

**Comment by adamdbradley** [comment]
There's actually two ways to do this. You could either bring up a modal which has it's own ion-nav inside of it, or set the config `tabSubPages` to true. Material design set's tabSubPages to true, but iOS does not because that's there defaults. The tabSubPages config should be in alpha.31. Also, @mhartington is working to document all of this for each of the respective config values.
