### ISSUE TITLE
Should we be able to add multiple headers to the same list or do we need a list divider component

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#418]
```html
  <ion-list>

    <ion-header>
    Today
    </ion-header>

    <ion-item>
        ...
    </ion-item>

    <ion-header>
    Last Week
    </ion-header>

</ion-list>
```

**or**

```html
  <ion-list>

    <ion-header>
    Today
    </ion-header>

    <ion-item>
        ...
    </ion-item>

    <list-divider>
    Last Week
    </list-divider>

</ion-list>

**Comment by mlynch** [comment]
I think we need to take a step back and rethink these component names. `<ion-header>` seems really generic.. What if we were more explicit?

```html
<ion-list>
  <ion-list-divider>
  </ion-list-divider>
</ion-list>
```

Or `<ion-item-divider>`. Thoughts?

**Comment by drewrygh** [comment]
Yeah I agree -- `<ion-header>` doesn't imply that it meant to be used with a list. If we are adding a divider component, can we remove the list header component, or does it do something a regular divider doesn't?


Also +1 for:

```html
<ion-list>
  <ion-list-divider>
  </ion-list-divider>
</ion-list>
```

it's explicit and reusable.

**Comment by adamdbradley** [comment]
Originally it was ion-header would work in both ion-list and ion-card, but we've since made an ion-card-header. So either we do only use ion-header, or it gets renamed to ion-list-header. Thinking more about it I think ion-list-header would be the way to go.

**Comment by mlynch** [comment]
I like `ion-list-header`. One more variable: groups. To make it easy to use tools like `ng-for`, we have to wrap groups in a container, and we use `ion-item-group-title`. Can we find some middleground here?

https://github.com/driftyco/ionic2/blob/master/ionic/components/list/test/sticky/main.html#L4

**Comment by adamdbradley** [comment]
I'd say ion-list-header is what you'd use instead of ion-item-group-title

**Comment by brandyscarney** [comment]
I think it's easier for the user to just say `ion-header` vs remembering `ion-list-header` and `ion-card-header` when they want to use those components. But at the same time if they put a list in a card we would have to make sure not to style the list header using the card headers styling and it may be confusing to them which header goes with which. 

So since they are going to be used and styled differently, I think it would be ok to name them differently. 

With that said, I think `ion-list-header` sounds like something you would use once in a list, not multiple times. And using `ion-list-header` inside of an `ion-item-group-title` is equally as confusing to me since it isn't really attached to the list, but to the `ion-item-group`. 

I think if we're going to be specific with the names of the headers we should go entirely specific (`ion-list-header`, `ion-card-header`, `ion-item-group-header`), or if we just want them to say "I want to use a header" we should just let them use `ion-header` everywhere and pick up the styling on our end.

**Comment by brandyscarney** [comment]
What was the final consensus on this?

**Comment by brandyscarney** [comment]
So we _could_ just have `ion-header` styled outside of a list and get rid of `ion-item-group-title` and `ion-card-header` then modify the styling when inside of a card or list.

**Comment by brandyscarney** [comment]
So `<ion-item-divider>` was added which can be used by itself as a divider or used to replace `<ion-item-group-title>` by using `<ion-item-divider sticky>`.

`<ion-header>` behaves and looks differently though so it still needs to be its own element. Really the only remaining question is should `<ion-header>` and `<ion-card-header>` be combined.

**Comment by brandyscarney** [comment]
Conclusion: `ion-header` will become `ion-list-header`, `ion-card-header` will remain the same, `ion-item-group-title` has been changed to `ion-item-divider sticky` and there is now an `ion-item-divider`. Let me know if there are any complaints.
