### ISSUE TITLE
Camera Plugin Not working

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#424]
I installed camera plugin using Cordova plugin add cordova-plugin-camera and it was added to plugins folder then in my code I tried to use below camera code which fails showing error in the xcode console saying ionic2.Camera.DesitnationType is undefined such sort of error

cordova-plugin-caimport {Camera} from 'ionic/ionic'

class PhotoTaker {
  takePhoto() {
    Camera.getPicture({
      quality: 50,
      destinationType: Camera.DestinationType.DATA_URL,
      sourceType: Camera.PictureSourceType.CAMERA,
      allowEdit: true,
      encodingType: Camera.EncodingType.JPEG,
      targetWidth: 100,
      targetHeight: 100,
      popoverOptions: CameraPopoverOptions,
      saveToPhotoAlbum: false
    }).then((data) => {
      // Camera data
      //let base64Image = "data:image/jpeg;base64," + data;
      // this.imageData = base64Image;
      //
      // Use this in your view: <img src="">
    })
  }
}

**Comment by ajaybeniwal** [comment]
Sorry My bad the issue is fixed

**Comment by Yagger** [comment]
Camera plugin is not working for me. I do exactly as doc specs http://ionicframework.com/docs/v2/platform/camera/
1. $ ionic plugin add cordova-plugin-camera
2. import {Camera} from 'ionic/ionic'
3. Camera.getPicture({...})

The error is this: "Cannot read property 'getPicture' of undefined".
I think this is not specific to Camera plugin, but rather to the import and paths. Because same happens with other plugins, like Vibration for example.

The only plugin that worked for me is Keyboard, but it did not require a plugin, it just importable from 'ionic/ionic' and injectable in constructor. I found the Keyboard using sample in forums somewhere, while according to docs http://ionicframework.com/docs/v2/platform/keyboard/ it is not injectable. So is the plugin supposed to be injectable or not? If not, then how do we test such code?

How exactly Camera is supposed to be exported by 'ionic/ionic'? Where 'plugin add' command places the Camera code so that it is available via 'ionic/ionic'.

My ionic-cli version is 2.0.0-beta.12
Ionic Framework version is 2.0.0-alpha.42
Angular version is 2.0.0-alpha.52
