### ISSUE TITLE
refactor list item border lines

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#437]
Using `:before` and `:after` for the border, and specifically having those borders have a `position:absolute` property is causing performance problems when scrolling. Redo list items so they just use border top and bottom.

Make sure the border is still there when an item is swiped open.

**Comment by brandyscarney** [comment]
Some tasks for me to keep track of:

iOS
- [x] Remove `position: relative;` from the item
- [ ] Checkbox and switch in inset list are not getting the content wrapped with the inner div
- [ ] `media-checkbox` margin is off could be affected by the above though ^ 
- [ ] inset list header not getting border radius
- [ ] item with a button in it has incorrect margin on the content
- [ ] Sticky headers & repeat headers: the header has a script tag after it preventing getting the first item to modify the border
- [ ] Since only the border top is being used, content with changing width `item-left`'s will change border, should we limit the selector to only do this for icons with `item-left`? 
- [ ] Random border not showing in the icons example

**Comment by brandyscarney** [comment]
Latest snapshot comparison: http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/sfpv/chrome_400x800#fa912653

**Comment by brandyscarney** [comment]
Latest snapshot: http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/oj49/chrome_400x800
