### ISSUE TITLE
button font size doesn't work 

### ISSUE THREAD

**Issue by felipereis** [driftyco/ionic2#466]
Button font size doesn't work for Android.
Ionic v2.0.0-alpha.15

![bug](https://cloud.githubusercontent.com/assets/2862216/11003796/e8568822-849b-11e5-8ae4-a107d5d8cf87.png)

**Comment by brandyscarney** [comment]
What's the markup on this?

**Comment by felipereis** [comment]
[code.txt](https://github.com/driftyco/ionic2/files/34135/code.txt)


p.s. keep up the good work XD

**Comment by brandyscarney** [comment]
Thanks :) 

So right now the reason it isn't working is because the `font-size` in `.md button` is taking priority. I opened an issue to discuss how we can make it easier for users to override these properties.

If you want a quick fix for now you can use:

```
.md .botaoSplash {
  font-size: 200%;
}
```

or you can use the `large` attribute which changes the font-size to `2rem`:

```
<button large></button>
```

and then override this value with the Sass variable: `$button-large-font-size`

A list of Sass variables you can override are in the docs: http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/

**Comment by brandyscarney** [comment]
Closing this because the CSS selector needs to be more specific to use your own classes, any discussion of this can go on #505
