### ISSUE TITLE
ionic serve giving error

### ISSUE THREAD

**Issue by advany** [driftyco/ionic2#526]
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file: /Users/abduladvany/apps/smeekbeden/webpack.config.js

./www/app/app.js
Module build failed: [object Object]
@ multi main (CLI v2.0.0-alpha.22)

Your system information:

Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.32
Ionic CLI Version: 2.0.0-alpha.22
Ionic App Lib Version: 2.0.0-alpha.21
ios-deploy version: Not installed
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite
Node Version: v4.2.1
Xcode version: Xcode 7.1.1 Build version 7B1005

**Comment by tlancina** [comment]
Any way you could track down what the object in `Module build failed: [object Object]` is? Otherwise there's not much way to tell what is wrong.

If you do `ionic start` and then `ionic serve` do you get this error? Or is this from a project started with an older version of the CLI or with modifications that you made?

**Comment by frederikschubert** [comment]
I now got the same error with the latest CLI version.
```
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file: /Users/frederik/Desktop/monitoring-app/webpack.config.js 

./www/app/app.js
Module build failed: [object Object]
 @ multi main (CLI v2.0.0-alpha.25)

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.37
Ionic CLI Version: 2.0.0-alpha.25
Ionic App Lib Version: 2.0.0-alpha.24
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite
Node Version: v5.0.0
Xcode version: Xcode 7.1.1 Build version 7B1005 
```

**Comment by tlancina** [comment]
@frederikschubert Any steps on how to reproduce?

**Comment by frederikschubert** [comment]
Yes I updated my dependencies and the issue was the update from typescript 1.6.2 to 1.7.3.
Reverting back to typescript 1.6.2 fixed the issue.

**Comment by tlancina** [comment]
Thanks @frederikschubert was able to reproduce this, it happens with typescript >1.7 and awesome-typescript-loader < 0.15 I believe (those versions may not be exact, but it happens when there is a mismatch).

This should be fixed in an upcoming release, although the lack of a meaningful message with `[object Object]` is a bug in awesome-typescript-loader I believe.

**Comment by tlancina** [comment]
We've updated Typescript and awesome-typescript-loader in the starters, so this shouldn't be an issue anymore.
