### ISSUE TITLE
Question - how to use Material Design by default?

### ISSUE THREAD

**Issue by bufke** [driftyco/ionic2#529]
Docs say "You can change the mode that gets assigned in the configuration of your app. Therefore, if you wanted the Material Design md mode on iOS, you could do it."

How is this done?

**Comment by adamdbradley** [comment]
The config docs are here: http://ionicframework.com/docs/v2/api/config/Config/. @mhartington is still working on the documentation to explain how this would work.

In your case, you could do this:

```
@App({
    config: {
        mode: 'md'
    }
})
```

**Comment by mhartington** [comment]
Currently,all the config docs are in the [config.ts file](https://github.com/driftyco/ionic2/blob/master/ionic/config/config.ts#L13)

So if you wanted to enable material design on all platforms, you can do

```
import {App,Config} from 'ionic/ionic';
import './app.scss';
@App({
  template: '<ion-nav [root]="root"></ion-nav>',
  config: {
    mode: 'md',
  }
})
export class MyApp {}
```

There are other methods you could do as well, if you wanted to do some some material design instead of the full implementation

You could configure any of these material design config properties, which are found in modes.ts
https://github.com/driftyco/ionic2/blob/master/ionic/config/modes.ts

```
actionSheetEnter: 'action-sheet-md-slide-in',
  actionSheetLeave: 'action-sheet-md-slide-out',
  actionSheetCancelIcon: 'ion-md-close',
  actionSheetDestructiveIcon: 'ion-md-trash',

  backButtonText: '',
  backButtonIcon: 'ion-md-arrow-back',

  iconMode: 'md',

  menuType: 'overlay',

  modalEnter: 'modal-md-slide-in',
  modalLeave: 'modal-md-slide-out',

  pageTransition: 'md',
  pageTransitionDelay: 120,

  popupEnter: 'popup-md-pop-in',
  popupLeave: 'popup-md-pop-out',

  tabbarHighlight: true,
  tabbarPlacement: 'top',

  tabSubPages: true,
```

**Comment by mhartington** [comment]
http://ionicframework.com/docs/v2/components/#modes
