### ISSUE TITLE
this.http not working on iOS device

### ISSUE THREAD

**Issue by jnosullivan** [driftyco/ionic2#546]
Hello, I am working on an app which involves gathering data from a rest backend, but for some reason the http is not running. When running 'ionic serve', the call is made, but not on mobile devices. In addition, console.log() is not writing to the console terminal on the mobile IDE. Any input would be much appreciated. 

John

**Comment by adamdbradley** [comment]
Would you be able to put together a minimal plunker that replicates the problem? Not sure if the issue is within Ionic2 or Angular2. This plunker is a good to fork from: http://plnkr.co/edit/yxPIh0hxhqhwjpsvqgid?p=preview

thanks

**Comment by mhartington** [comment]
This could be a case of apples ATS preventing the call

**Comment by jnosullivan** [comment]
This what I'm doing, I'm posting JSON login data to receive a user profile off a server. Is this http syntax correct?

import {Http, Headers} from 'angular2/http';


constructor(nav: NavController, http: Http) {
this.http = http;
this.loginData = {username:"",password:""};
}

login() {

this.http.post('URL',JSON.stringify(this.loginData)).map(res => res.json()).subscribe(
      data => console.log(data),
      err => console.log(err),
      () => console.log('Got Data')
);

}

**Comment by robwormald** [comment]
@jnosullivan out of curiosity, what was the failure state here? does it just die silently or return some sort of meaningful error? might be able to handle it better on the angular2 end.

**Comment by Ionitron** [comment]
Greetings @jnosullivan!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using Ionic, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.
