### ISSUE TITLE
How to Exit Tab Bar Page within a SideBar Template 

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#621]
I have Sidemenu template as my main outer template but inside one of the pages I am using Tabbar template to display some UI , but currently I am not able to exit the tab par template using this.nav.pop() so my question is how to handle this situation and return back to side menu pages from Tab par inner page

**Comment by adamdbradley** [comment]
One way is to put an `id="root-nav"` on the root ion-nav, then use `app.getComponent('root-nav')` to get the instance and call `nav.pop()`.

I also just made it possible by climbing up the NavControllers which your tab pages would be, then calling `pop()`. For example, a sign in page would be the first page in the root nav, and the `ion-tabs` would be the second page in the root nav. Then the first `ion-tab` would load, which would have the first page in `ion-tab`. So that first page in the tabs could call `this.nav.parent.parent.pop()`.

Here's a quick example: https://github.com/driftyco/ionic2/blob/master/ionic/components/tabs/test/advanced/index.ts#L67
