### ISSUE TITLE
Can't install ionic2 trough jspm anymore since alpha.34

### ISSUE THREAD

**Issue by vadimpopa** [driftyco/ionic2#662]
@tlancina is there any reason for this commit: https://github.com/driftyco/ionic2/commit/de5f4b98ca8797a5a707c6a4341192859232e8e9

I use jspm and now I get a jspm install (missing in registry) error when trying to install ionic2:

```javascript
warn Error on processPackageConfig
     Package.json dependency angular2 set to github:tlancina/angular-package, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.
```

**Comment by vadimpopa** [comment]
Hey @tlancina could you please let me know when will have the angular2 registry name back ? and if possible a few words why you guys patched it for now. Thanks.

**Comment by tlancina** [comment]
@vadimpopa, didn't realize this broke jspm, but I believe this is a jspm bug because github is a valid format for npm dependencies: https://github.com/jspm/npm/issues/101.

It is only temporary until https://github.com/angular/angular/pull/5520 lands.  I believe the patch fixes some flicker issues with animations.

I'll leave this open until we remove the patched version in case other people run into this as well.

**Comment by vadimpopa** [comment]
ok, thanks, hopefully that flicker issue will be solved soon.

**Comment by astec** [comment]
@mlynch, the https://github.com/angular/angular/pull/5520 is not passing all checks - merge from master needed.

**Comment by tlancina** [comment]
Should no longer be an issue.

**Comment by vadimpopa** [comment]
awesome @tlancina , thanks.
