### ISSUE TITLE
Auto Scroll to bottom on adding of new event

### ISSUE THREAD

**Issue by gondar00** [driftyco/ionic2#717]
I am trying to create a chat application and i would like the page to auto scroll to the bottom when i add a message is it possible in v2 just like $ionScrollDelegate?

**Comment by Ionitron** [comment]
Greetings @gondar00!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic.

This GitHub issue tracker is used to track Ionic features, problems, and development.  

If you wish to get help using Ionic, the recommended place is [the forum](http://forum.ionicframework.com) or [Ionic Worldwide on Slack](http://ionicworldwide.herokuapp.com/). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
