### ISSUE TITLE
How can I create a projecto only with Javascript?

### ISSUE THREAD

**Issue by mrkaspa** [driftyco/ionic2#730]
This command: ionic start ionic2-delete --v2 , used to create the project with JS but now it creates it with TS. What can I do?

**Comment by brandyscarney** [comment]
The starters have been updated back to use JS by default. Please try creating an app now and let us know if you have problems. An additional step is required at the moment in order to build the CSS, please make sure you have `gulp` installed and run `gulp sass` to build the css or `gulp sass watch` to watch for changes to the Sass.

View the conference app for more details: https://github.com/driftyco/ionic-conference-app#getting-started

**Comment by mrkaspa** [comment]
@brandyscarney the sass-webpack support has been removed?

**Comment by mrkaspa** [comment]
Also I'm getting problems with the new template #732

**Comment by brandyscarney** [comment]
Yes we've removed Sass building from webpack in favor of using gulp because of some issues with using webpack.
