### ISSUE TITLE
Minifying the app.bundle.js and the css files automatically during ionic build

### ISSUE THREAD

**Issue by krz37** [driftyco/ionic2#774]
Minifying the app.bundle.js and the css files automatically would drastically reduce de size and so the load of the JS and CSS files. HTML could also be included but I guess it needs a bit too much work compared to the outcome it would bring

**Comment by tlancina** [comment]
@krz37 so I'm not sure this is a good idea during development because it would take a significantly longer time to reminify the bundle on every single change.  For a good idea of the time difference, compare the running time of `webpack` and `webpack -p`, and that is without CSS minification.

What if instead there was a production CLI option, you run it when you are ready to deploy your app into production and would handle minifying all of your assets?

**Comment by krz37** [comment]
@tlancina That's right yes. Do you think it could be included in the "ionic build --release android" for example? A CLI option could be very nice as well.
Another thing I notice is that currently the JS is included 2 times in the APK. If I am not mistaking it is in the /build/app.bundle.js and all the .js written are kept in /app when you extract it.

**Comment by tlancina** [comment]
@krz37 ah sorry I see the issue was for `build` specifically.  Yes I like the idea of doing it then, since the only time you would be using `build` is to release, if I understand it correctly (since `run` and `emulate` will compile for you automatically).

Regarding the code duplication, that should go away soon as we're most likely going to pull `app` out of `www`. You can take a look at https://github.com/driftyco/ionic-conference-app/issues/98 for more of the discussion there.

**Comment by krz37** [comment]
Thank you

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5044
