### ISSUE TITLE
Blank screen during the loading (splashscreen was working earlier)

### ISSUE THREAD

**Issue by krz37** [driftyco/ionic2#775]
When coding against the last beta starter (but I think it might be related to Ionic), I get a white screen instead of my generated splashscreens.
The issue was also mentioned here https://forum.ionicframework.com/t/ionic2-app-show-blank-screen-on-android-device-4-2-2-using-run-command-and-ionicview/39405/3

**Comment by mhartington** [comment]
Could you post the following outputs.

```
ionic info 
ionic plugin ls
ionic platform ls
```

Also, how could I got about recreating this?

**Comment by krz37** [comment]
Sorry I was travelling.

ionic info : 
> Cordova CLI: 5.4.1
> Ionic CLI Version: 2.0.0-beta.12
> Ionic App Lib Version: 2.0.0-beta.6
> OS: Distributor ID:	ManjaroLinux Description:	Manjaro Linux 
> Node Version: v5.1.1

ionic plugin ls : 
> cordova-sqlite-storage 0.7.14 "Cordova sqlite storage plugin"

ionic platform ls : 
> Installed platforms: android 4.1.1, ios 3.9.2
> Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ubuntu, webos

Steps that I took :
> $ ionic start cutePuppyPics --v2
> $ cd cutePuppyPics
> $ ionic serve ---> No splashscreen
> $ ionic build android ---> No splashscreen

**Comment by krz37** [comment]
I generated with
> ionic resources

But it also does the same with the default conf so when I put the steps of the default conf I followed for my second test above.

**Comment by mhartington** [comment]
Hmm, wasn't able to replicate this. 

```
ionic start tmp --v2
ionic platform add android
ionic run android --device
ionic resources
ionic run android --device
```
App started with the first time with the default cordova splash screen, then started up the second time with the ionic splash screen instead. 

Could you try again?

**Comment by krz37** [comment]
Sorry I cannot try now since I do not have the device or the code with me. Only on Wednesday next week.
However, other people have the same issue here : https://forum.ionicframework.com/t/ionic2-app-show-blank-screen-on-android-device-4-2-2-using-run-command-and-ionicview/39405/6

**Comment by mhartington** [comment]
is this similar to https://github.com/driftyco/ionic2/issues/794?

**Comment by krz37** [comment]
No it isn't. I had this issue on the latest MIUI and Cyanogen 12.1 beta. I am soon back home so I will test with the latest beta of Ionic 2 tomorrow

**Comment by krz37** [comment]
Works fine in the last beta for me now

**Comment by Ionitron** [comment]
Greetings @krz37!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using Ionic, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.
