### ISSUE TITLE
Fix the title on iOS

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#820]
Need to figure out a way to fix the title on iOS. What if to fix the title on iOS (it always needs to be centered), we added the `start/end` buttons with the same width all of the time so even if they didn't have content they would still take up the same space, then we can add flex properties to the `toolbar-content` and the title won't need the padding or absolute positioning. I'm going to look into more ways to do this.

**Comment by mlynch** [comment]
I don't think absolutely positioning and doing the centering with JS is a bad approach. It's likely the same one that is being done natively, since there isn't really a natural way to express the way iOS title bar centering works through layout containers AFAICT

**Comment by adamdbradley** [comment]
Yes it'll have to use JS to center the content by adding padding to either the left or right side. This is already what v1 does, and v2 will have to do. The challenge is that the css is applied to all the inner buttons, which may or may not be accurate when you do a Dom read (it'll probably report a width of zero for a frame). Once you do finally get accurate widths of the back button, menu button, and all start/end buttons, you then need to apply the css update to the title. All of this is absolutely possible, but to do all these Dom reads and writes during a transition causes some ugly jank and you see the title adjust as it sides in. So all of this needs to happen before the transition, which still has the same issues of coordinating reads and writes while the view itself is being written, then waiting for the css to apply before kicking off the transition, all without jank. So as it stands it first defaults to full width with some best guess for padding that works in most cases. But as you see it doesn't work for all cases. So solving this will take some time like v1's did, but it's very important it's tested on iOS devices, and the Dom reads and writes are coordinated with the view creation and animation starting. Additionally, because we're manually adding styles to the title, they'll have to be cleared out since the Dom elements may or may not be reused by ng2's view pool.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5036
