### ISSUE TITLE
Please someone can help me? i search how to handle the return object, and how to use the post, update, and delete methods to invoke rest service in Ionic2.

### ISSUE THREAD

**Issue by FellagIng** [driftyco/ionic2#840]

**Comment by Ionitron** [comment]
Greetings @FellagIng!

My sensors indicate that you have created an issue on our tracker requesting usage help, rather than an actual error with Ionic.

This GitHub issue tracker is used to track Ionic features, problems, and development.  

If you wish to get help using Ionic, the recommended place is [the forum](http://forum.ionicframework.com) or [Ionic Worldwide on Slack](http://ionicworldwide.herokuapp.com/). There are many humans there who would be happy to offer sage advice.

Thank you for allowing me to assist you.
