### ISSUE TITLE
Modal transition

### ISSUE THREAD

**Issue by arashbi** [driftyco/ionic2#845]
I have a login use case where I present the user with login modal, and there is a link for sign up. When the user click the sign up, application should close the modal and transition the user to sign up page.
simply calling 
         this.close();
        this.modal.open(SignupModal,{},{handle : 'signup'});
Just closes the login and doesn't open the sign up

**Comment by Ionitron** [comment]
Greetings @arashbi!

I'm sorry, but my sensors indicate that this issue may no longer apply to recent versions of Ionic.

If you are still experiencing this issue, please feel free to reopen it by creating a new issue and provide the following information, so that I may assist you:

- Can you provide a detailed description of this issue?
- How would a robot go about replicating this issue?
- On which platform does this occur? (iOS, Android, all, etc.)
- On which platform versions does this occur? (Android 4.2, iOS 7, all, etc.)
- Is this an issue with the Ionic Framework or Ionic CLI?

Additionally, providing a [codepen](http://codepen.io/ionic/public-list/) that replicates the issue is extremely helpful.

If you wish to get help using Ionic, I recommended visiting [the forum](http://forum.ionicframework.com). There are many humans there who can offer sage advice.

Thank you for allowing me to assist you.
