### ISSUE TITLE
Ionicon V3 not working if icon name contains an hyphen 

### ISSUE THREAD

**Issue by zamrokk** [driftyco/ionic2#862]
here is a snippet of my code : 
```
 <ion-tab tabIcon="plane" tabTitle="Trips" [root]="tabTrips"> </ion-tab>
 <ion-tab tabIcon="qr-scanner" tabTitle="Smart Scan" [root]="tabSmartScan" ></ion-tab>
   ```
both icons exists on the scss file
line 1 : success
line 2 : failure

any name i use with an hyphen is failing in fact

please do something, it should not be so hard to fix it

**Comment by mhartington** [comment]
Not able to replicate. Do you have an example repo that we could look at?

**Comment by zamrokk** [comment]
can you access this link ?

https://hub.jazz.net/project/bfuentes/ibmExpenses/overview

It should be public

**Comment by mhartington** [comment]
Ahh alright, so it happens when the icon does not have an outline version. Also, it seem that icons will automatically append `-outline` to the icon name if it is not selected, https://github.com/driftyco/ionic2/blob/master/ionic/components/icon/icon.ts#L105

@adamdbradley we could change this or make sure that all the icons have an outline version.
