### ISSUE TITLE
Translate support

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic2#883]
It would be nice to have multi language support built in.
You know, like "Back" text in back button or "OK" in alert popup.
And support for my own text in app...

**Comment by adamdbradley** [comment]
The back button text can be configured using the config: http://ionicframework.com/docs/v2/api/config/Config/

The alert can be given any text for the button:
http://ionicframework.com/docs/v2/api/components/alert/Alert/

We also have a small translation provider here: https://github.com/driftyco/ionic2/tree/master/ionic/translation

Additionally, the Angular team will also building out a more robust one and the doc can be found here: https://docs.google.com/document/d/1mwyOFsAD-bPoXTk3Hthq0CAcGXCUw-BtTJMR4nGTY-0/view

Related: #798

**Comment by MatanYed** [comment]
#adamdbradley I know that there is configure options and will be translation module. I just thought it would be nice to have a config option to make it automatically. Don't you think so it would be great? You choose systen language as arabic - it will automatically be RTL, system texts will be in arabic...

**Comment by adamdbradley** [comment]
Yeah that is a good idea, like from the CLI's start command? Something like

`ionic start myapp --rtl` ??

**Comment by MatanYed** [comment]
More like:

@App({
  config: {
    language: 'en_US'
  }
});

**Comment by adamdbradley** [comment]
Yeah I think that's a good idea to have our starters already come with the `config` ready to be filled in, however I don't think `dir` and `lang` should be within the config, only because those should be hardcoded within the html the moment the HTML loads, and well before Ionic and angular are initialized and running. 

For example, if there was some splashcreen HTML that was shown while the app is starting up, and Ionic's config hasn't run yet, then when ionic switches it to RTL, it'd be pretty janky when the entire app rerenders.

Related #832

**Comment by astec** [comment]
Also I think the UI language should be defined on user/session level, not an app so it has no place in config. But there could be some "currentLanguage" or "defaultLanguage".

It would be nice if strters & Ionic conference app support multi-lang (at least 2 languages = English + something). Ideally English + LTR (non English) + RTL.

**Comment by adamdbradley** [comment]
Good point @astec, it's user/session thing, not an app config. What we can do is add some methods to `Platform` so language and direction can be updated though Ionic instead of manually updating the DOM directly (which is a no-no for future web worker and universal app support)

https://github.com/driftyco/ionic2/issues/887

**Comment by adamdbradley** [comment]
Related: https://github.com/driftyco/ionic2/issues/888
