### ISSUE TITLE
How i imput correctly angular2 pluggins?

### ISSUE THREAD

**Issue by uiktiomasfeliz** [driftyco/ionic2#920]
I tried to implement ng2-material into a ionic2 project without success.
What file i need to edit for the correct implementation?

**Comment by mhartington** [comment]
I don't believe angular2-material is in any usable state right now, so I wouldn't try to use that. But for any other library, you would just npm install it, and reference the folder name, and the entry point. 

For example, when we import `Http` we do 

```
import {Http} from 'angular2/http';
```
Because there's a angular2 directory in our node modules, and a entry point of http.js

<img width="498" alt="screen shot 2016-01-12 at 8 11 44 am" src="https://cloud.githubusercontent.com/assets/2835826/12269023/354445ba-b904-11e5-8b27-063694ca735d.png">

**Comment by uiktiomasfeliz** [comment]
thanks
