### ISSUE TITLE
Create d.ts file for swiper-widget

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#934]

**Comment by adamdbradley** [comment]
https://github.com/driftyco/ionic2/blob/master/ionic/components/slides/swiper-widget.ts

**Comment by tlancina** [comment]
Still very new to TypeScript so it's possible there is a way to do this, but I believe we can't just add the types inline to Swiper because TypeScript won't create a type for es5 functions (constructor or no): https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Declaration%20Merging.md#basic-concepts, meaning if we want type information for Swiper instances like [slides](https://github.com/driftyco/ionic/blob/2.0/ionic/components/slides/slides.ts#L86) we'll need to create a separate .d.ts file describing Swiper's "shape".

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5008
